service: serverless-example

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

custom:
  esbuild:
    # plugins : ./plugins.js
    external:
       - lodash
       - openpgp
    packager: npm
    bundle: true
    minify: false
    sourcemap: true
    keepNames: true

functions:
  hello1:
    handler: hello1.handler
    events:
      - http:
          path: hello
          method: get

  hello2:
    handler: hello2.handler
    events:
      - http:
          path: hello
          method: get
