service: serverless-example

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: false

provider:
  name: aws
  runtime: nodejs12.x

custom:
  esbuild:
    plugins : ./plugins.js
    packager: yarn
    bundle: true
    minify: false
    sourcemap: true
    keepNames: true
    packagerOptions:
      scripts:
        - npm install -g clean-modules
        - clean-modules -y --exclude \"test.js\" \"**/*.map.js\" --include \"**/*.d.ts\"
functions:
  hello1:
    handler: hello1.handler
    events:
      - http:
          path: hello
          method: get

  hello2:
    handler: hello2.handler
    events:
      - http:
          path: hello
          method: get
